export {default as Home} from "./Home"
export {default as SupervisorTopic} from "./SupervisorTopic";
export {default as SearchTopic} from "./SearchTopic";
export {default as AddTopic} from "./AddTopic"
export {default as StaffDetails} from "./StaffDetails";
export {default as StaffTopics} from "./StaffTopics";
export {default as StaffStudents} from "./StaffStudents";
export {default as StaffUpdateProfile} from "./StaffUpdateProfile"
export {default as AdminLogin} from "./Admin/AdminLogin"
export {default as AdminStaffs} from "./Admin/AdminStaffs"
export {default as AdminStudents} from "./Admin/AdminStudents"
